version: '3'

services:
  test:
    image: ofnet/test
    working_dir: /go/src/ofnet
    command: make test
    privileged: true
    volumes_from:
      - ovsdb-server
    network_mode: "host"
    depends_on:
      - ovs-vswitchd
