name: ci

on:
  pull_request:
    branches:
      - '*'

  push:
    branches:
      - '*'

jobs:
  pr-check:
    runs-on: [ self-hosted, pod ]

    steps:
      - uses: actions/checkout@v2
      - run: make docker-build
      - run: make docker-test
